version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: sc4013_postgres_db_container
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db_schema:/docker-entrypoint-initdb.d

volumes:
  postgres_data: