version: '3'

services:
  # This service will watch for changes in the image version
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  sc4013-be:
    image: registry.digitalocean.com/sc4013/sc4013-backend:latest
    container_name: sc4013_backend
    env_file:
      - .env
    ports:
      - "80:3000"
    volumes:
      - ./config_files/:/usr/src/app/config_files/
  postgres:
    image: postgres:latest
    container_name: sc4013_postgres_db_container
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db_schema:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
