
# Connect to PostgreSQL and create the user and schema
psql -U "$POSTGRES_USER" -d "$POSTGRES_DB" <<EOF
CREATE USER $POSTGRES_RW_USER WITH PASSWORD '$POSTGRES_RW_PASSWORD';
CREATE SCHEMA IF NOT EXISTS $DB_SCHEMA AUTHORIZATION $POSTGRES_RW_USER;
GRANT USAGE ON SCHEMA $DB_SCHEMA TO $POSTGRES_RW_USER;
ALTER DEFAULT PRIVILEGES IN SCHEMA $DB_SCHEMA
    GRANT SELECT, INSERT, UPDATE ON TABLES TO $POSTGRES_RW_USER;
ALTER DEFAULT PRIVILEGES IN SCHEMA $DB_SCHEMA
    GRANT USAGE, SELECT ON SEQUENCES TO $POSTGRES_RW_USER;
EOF