-- Create User table
CREATE TABLE "User" (
    ID SERIAL PRIMARY KEY,
    Email VARCHAR(100) NOT NULL,
    Password VARCHAR(1000) NOT NULL,
    Salt VARCHAR(32) NOT NULL,
    Last_password_change TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    Created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    Last_login TIMESTAMP,
    Lockout CHAR(1) NOT NULL DEFAULT 'N',
    IsAdmin CHAR(1) NOT NULL DEFAULT 'N'
);

CREATE TABLE Product
(
    id          SERIAL PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    description VARCHAR(1000),
    createdBy   INT          REFERENCES "User" (ID) ON DELETE SET NULL,
    updatedBy   INT          REFERENCES "User" (ID) ON DELETE SET NULL,
    createdAt   TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt   TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deletedAt   TIMESTAMPTZ  NULL     DEFAULT NULL
);
