-- Create User table
CREATE TABLE "User" (
    ID SERIAL PRIMARY KEY,
    Email VARCHAR(100) NOT NULL,
    Password VARCHAR(1000) NOT NULL,
    Salt VARCHAR(32) NOT NULL,
    Last_password_change TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    Created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    Last_login TIMESTAMP,
    Lockout CHAR(1) NOT NULL DEFAULT 'N',
    IsAdmin CHAR(1) NOT NULL DEFAULT 'N'
);

-- Create Product table
CREATE TABLE "Product" (
    ID SERIAL PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Description VARCHAR(1000),
    Updated_by INT REFERENCES "User"(ID) ON DELETE SET NULL,
    Created_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    Updated_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);