
# Connect to PostgreSQL and create the user and schema
psql -U "$POSTGRES_USER" -d "$POSTGRES_DB" <<EOF
ALTER TABLE $DB_SCHEMA."User" OWNER TO $POSTGRES_RW_USER;
ALTER TABLE $DB_SCHEMA.Product OWNER TO $POSTGRES_RW_USER;

GRANT SELECT, INSERT, UPDATE ON $DB_SCHEMA."User" TO $POSTGRES_RW_USER;
REVOKE DELETE ON $DB_SCHEMA."User" FROM $POSTGRES_RW_USER;

GRANT SELECT, INSERT, UPDATE ON $DB_SCHEMA.Product TO $POSTGRES_RW_USER;
REVOKE DELETE ON $DB_SCHEMA.Product FROM $POSTGRES_RW_USER;

ALTER USER $POSTGRES_RW_USER SET search_path TO $DB_SCHEMA, public;
EOF